config/routes.rb
CSC667project::Application.routes.draw do
  resources :appointments

  get "pages/calendar"

  get "pages/project_2" => "pages#project_2"

  get "/calendar" => "pages#calendar"

  get "appointments" => "appointments#index"
  post "/appointments" => "appointments#create"

  root 'pages#home'

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    if params['month'].present? and params['year'].present?
      @appointments = Appointment.where('month' => params['month'], 'year' => params['year']).to_a
      # respond_to do |format|
      #   format.html { redirect_to @appointments, notice: 'Appointments were received.' }
      #   format.json { render action: 'show', status: :received, location: @appointments }
      # end
    else
      @appointments = Appointment.all
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      #params.require(:appointment).permit(:day, :month, :year, :time, :description)
      params.permit(:day, :month, :year, :time, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def project_2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<%= link_to 'Back', appointments_path %>

<!-- <table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Month</th>
      <th>Year</th>
      <th>Time</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.day %></td>
        <td><%= appointment.month %></td>
        <td><%= appointment.year %></td>
        <td><%= appointment.time %></td>
        <td><%= appointment.description %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %> -->

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @appointment.day %>
</p>

<p>
  <strong>Month:</strong>
  <%= @appointment.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @appointment.year %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joe Robinson - CSC667project</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/.html.erb
<h1>Pages#/</h1>
<p>Find me in app/views/pages/.html.erb</p>

app/views/pages/calendar.html.erb
<div class = "col-md-12">
    <div class = "page-header">
        <h1>Joe Robinson - CSC 667</h1>
    </div>
    <div class = "row">
        <div class = "col-md-12">
            <form class = "form-horizontal" role = "form">
                <div class="form-group">
                    <label for="input_time" class="col-md-2 control-label">Time</label>
                    <div class = "col-md-4">
                        <input class="form-control" id="input_time">
                    </div>
                </div>
                <div class="form-group">
                    <label for="input_description" class="col-md-2 control-label">Description</label>
                    <div class = "col-md-4">
                        <input class="form-control" id="input_description">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class = "col-md-12">
        <table class = "table table-bordered" id = "calendar">
            <tr id  = "controls">
                <td align = "center" colspan = "1"> 
                    <button type="button" class="btn btn-primary" id = "dec_year"> << </button>
                </td>
                <td align = "center" colspan = "1">
                    <button type="button" class="btn btn-primary" id = "dec_month"> < </button>
                </td>
                <td align = "center" colspan = "3"> <p id = "month_year"> </p> </td>
                <td align = "center" colspan = "1">
                    <button type="button" class="btn btn-primary" id = "inc_month"> > </button>
                </td>
                <td align = "center" colspan = "1">
                    <button type="button" class="btn btn-primary" id = "inc_year"> >> </button>
                </td>
            </tr>
            <tr>
                <td align = "center"> Sun </td>
                <td align = "center"> Mon </td>
                <td align = "center"> Tue </td>
                <td align = "center"> Wed </td>
                <td align = "center"> Thu </td>
                <td align = "center"> Fri </td>
                <td align = "center"> Sat </td>
            </tr>
        </table>
    </div>
</div>

app/views/pages/home.html.erb
<div class = "col-md-12">
    <div class = "page-header">
        <h1>Joe Robinson - CSC 667</h1>
    </div>

    <div class = "row">
        <div class = "col-md-6">
            <table class = "table table-striped">
                <tbody>
                    <tr>
                        <td><b>Project name</b></td>
                        <td><b>Description</b></td>
                        <td><b>Url</b></td>
                    </tr>
                <% Projects.each do |project|%>
                    <tr>
                        <td><%= project[0] %> </td>
                        <td><%= project[1]["description"] %> </td>
                        <td><%= link_to project[1]["url"], project[1]["url"] %> </td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/pages/project_2.html.erb
<div class = "col-md-12">
    <div class = "page-header">
        <h1>Joe Robinson - CSC 667</h1>
    </div>
    <div class = "col-md-6">
        <ol class = "list-group">
            <li class = "list-group-item">1. Verified jQuery already existed in the rails app.</li>
            <li class = "list-group-item">2. Use "bootstrap-sass-rails" gem for Twitter Bootstrap access. </li>
            <li class = "list-group-item">3. Updated application.js and application.css to require Bootstrap. </li>
            <li class = "list-group-item">4. Added project_2 action, route, and view. </li>
        </ol>
    </div>
</div>